[package]
name = "disney_hls_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
[dependencies]
anyhow = "1"

[dev-dependencies]
indoc = "2"
